/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2018-12-27 06:08:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contactus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<style>\r\n");
      out.write("font-family: 'Roboto ', sans-serif ;\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #D9B280;\r\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 {\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\theight: 650px;\r\n");
      out.write("\tmargin: 5% auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .map {\r\n");
      out.write("\twidth: 45%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form {\r\n");
      out.write("\twidth: 53%;\r\n");
      out.write("\tmargin-left: 2%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form .title {\r\n");
      out.write("\tfont-size: 2.5em;\r\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tcolor: #242424;\r\n");
      out.write("\tmargin: 5% 8%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form .subtitle {\r\n");
      out.write("\tfont-size: 1.2em;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tmargin: 0 4% 5% 8%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form input, .container1 .contact-form textarea {\r\n");
      out.write("\twidth: 330px;\r\n");
      out.write("\tpadding: 3%;\r\n");
      out.write("\tmargin: 2% 8%;\r\n");
      out.write("\tcolor: #242424;\r\n");
      out.write("\tborder: 1px solid #B7B7B7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form input::placeholder, .container1 .contact-form textarea::placeholder\r\n");
      out.write("\t{\r\n");
      out.write("\tcolor: #242424;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 .contact-form .btn-send {\r\n");
      out.write("\tbackground: #fcc99b;\r\n");
      out.write("\twidth: 180px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tmargin: 2% 8%;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"container1\">\r\n");
      out.write("\t\t<div class=\"map\">\r\n");
      out.write("\t\t\t<iframe\r\n");
      out.write("\t\t\t\tsrc=\"https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=annai%20medical%20oppo%2C7th%20street%2Cgandhipuram%2C%20coimbatore+(Flower%20Paradise)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=A&amp;output=embed\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"600px\" frameborder=\"0\" style=\"border: 0\"\r\n");
      out.write("\t\t\t\tallowfullscreen></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"contact-form\">\r\n");
      out.write("\t\t\t<h1 class=\"title\">Contact Us</h1>\r\n");
      out.write("\t\t\t<h2 class=\"subtitle\">We are here assist you.</h2>\r\n");
      out.write("\t\t\t<form action=\"sendmail\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Your Name\" />\r\n");
      out.write("\t\t\t\t<input type=\"email\" id=\"e-mail\" name=\"e-mail\" placeholder=\"Your E-mail Adress\" />\r\n");
      out.write("\t\t\t\t<input type=\"tel\" id=\"phno\"\r\n");
      out.write("\t\t\t\tname=\"phno\" placeholder=\"Your Phone Number\" />\r\n");
      out.write("\t\t\t\t<textarea id=\"message\" name=\"message\" rows=\"8\" placeholder=\"Your Message\"></textarea>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn-send\">Get a Call Back</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
